


object Bounds {
    attribute double l;
	attribute double b;
	attribute double r;
	attribute double t;
};

[Internal="MSDFFontMetrics"]
object FontMetrics {
	FontMetrics new();

	attribute int ascent;
	attribute int descent;
	attribute int unitsPerEm;
	attribute int baseLine;
	attribute int lineHeight;
	attribute int flags;
};

object GlyphMetrics {
	GlyphMetrics new();
	
	attribute int width;
	attribute int height;
	attribute int offsetX;
	attribute int offsetY;
	attribute int advanceX;
	attribute int descent;
	attribute bool ccw;
};

[Internal="MSDFFont"]
object Font {
	bool getGlyphMetrics(int charcode, GlyphMetrics *metrics);
	int getKerning(int left, int right);
	String getName();
	FontMetrics *getMetrics();
};

object FontLibrary {
	FontLibrary new();
	Font *load(String filename, int fontSize);
	void unloadAll();
};


object Atlas {
	Atlas new();

	void begin(int atlasWidth, int atlasHeight, int defaultColor, bool enforceR8);
	void end();

	bool generateSDFGlyph(Font *font, int charcode, int width, int height, int ox, int oy, double tx, double ty, bool ccw, double range);
	bool generatePSDFGlyph(Font *font, int charcode, int width, int height, int ox, int oy, double tx, double ty, bool ccw, double range);
	bool generateMSDFGlyph(Font *font, int charcode, int width, int height, int ox, int oy, double tx, double ty, bool ccw, double range);
	bool rasterizeGlyph(Font *font, int charcode, int width, int height, int ox, int oy);

	bool generateSDFPath(Shape *shape, double width, double height,  int ox, int oy, double tx, double ty, double range, double scale);
	bool generateMSDFPath(Shape *shape, double width, double height,  int ox, int oy, double tx, double ty, double range, double scale);
	bool generatePSDFPath(Shape *shape, double width, double height,  int ox, int oy, double tx, double ty, double range, double scale);

	int imageByteCount();
	void copyImage( bytes data );

};

[Internal="MSDFShape"]
object Shape {
	Bounds getBounds();
};

object ShapeLibrary {
	ShapeLibrary new();
	Shape *loadSvgShape(String path, int fontSize, double scale, double endpointSnapRange);
};